version: 1.0.{build}

platform: 
 - x86
 - x64
configuration: 
 - Debug
 - Release
 
build_script:
 - c:\mingw\bin\mingw-get install mingw32-autoconf 
 - c:\mingw\bin\mingw-get show
 - c:\mingw\bin\make
